//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomBooking.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomBooking.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên đã phê duyệt yêu cầu đặt phòng của bạn. Dưới đây là thông tin chi tiết về yêu cầu đặt phòng của bạn:.
        /// </summary>
        public static string AdminBrowser {
            get {
                return ResourceManager.GetString("AdminBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3D75DE.
        /// </summary>
        public static string BrowseColor {
            get {
                return ResourceManager.GetString("BrowseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E0E0E0.
        /// </summary>
        public static string CancelColor {
            get {
                return ResourceManager.GetString("CancelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại trong hệ thống..
        /// </summary>
        public static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại trong hệ thống..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn có bất kỳ câu hỏi hoặc yêu cầu hỗ trợ nào, vui lòng liên hệ với chúng tôi để được hỗ trợ..
        /// </summary>
        public static string EmailFooter {
            get {
                return ResourceManager.GetString("EmailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi rất tiếc vì không thể đáp ứng được nhu cầu của bạn lần này. Nếu bạn có bất kỳ câu hỏi hoặc yêu cầu hỗ trợ nào, vui lòng liên hệ với chúng tôi để được hỗ trợ..
        /// </summary>
        public static string EmailFooterCancel {
            get {
                return ResourceManager.GetString("EmailFooterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi xin thông báo rằng đơn đặt phòng của bạn đã được hủy thành công. Dưới đây là thông tin chi tiết về đơn đặt phòng của bạn:.
        /// </summary>
        public static string EmailHeaderCancel {
            get {
                return ResourceManager.GetString("EmailHeaderCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đặt phòng của bạn đã được chuyển cho quản trị viên phê duyệt. Dưới đây là thông tin chi tiết về yêu cầu đặt phòng của bạn:.
        /// </summary>
        public static string EmailHeaderInsert {
            get {
                return ResourceManager.GetString("EmailHeaderInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi xin thông báo đơn đặt phòng của bạn đã được .
        /// </summary>
        public static string EmailHeaderRequest {
            get {
                return ResourceManager.GetString("EmailHeaderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đặt phòng của bạn đã cập nhật thành công và được chuyển cho quản trị viên phê duyệt. Dưới đây là thông tin chi tiết về yêu cầu đặt phòng của bạn:.
        /// </summary>
        public static string EmailHeaderUpdate {
            get {
                return ResourceManager.GetString("EmailHeaderUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ nhân viên kĩ thuật để được hỗ trợ!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ. Vui lòng kiểm tra lại!.
        /// </summary>
        public static string Error_DataInputIsError {
            get {
                return ResourceManager.GetString("Error_DataInputIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string ErrorDuplicate {
            get {
                return ResourceManager.GetString("ErrorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldEmpty.
        /// </summary>
        public static string ErrorEmpty {
            get {
                return ResourceManager.GetString("ErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInput.
        /// </summary>
        public static string ErrorInput {
            get {
                return ResourceManager.GetString("ErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldLimitLenght.
        /// </summary>
        public static string ErrorLimitLength {
            get {
                return ResourceManager.GetString("ErrorLimitLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại trong hệ thống..
        /// </summary>
        public static string IsDuplicateCode {
            get {
                return ResourceManager.GetString("IsDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại trong hệ thống..
        /// </summary>
        public static string IsErrorDuplicateMutiple {
            get {
                return ResourceManager.GetString("IsErrorDuplicateMutiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string IsErrorEmail {
            get {
                return ResourceManager.GetString("IsErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép để trống..
        /// </summary>
        public static string IsErrorEmptyMultiple {
            get {
                return ResourceManager.GetString("IsErrorEmptyMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã vượt quá {1} kí tự..
        /// </summary>
        public static string IsErrorLimitLength {
            get {
                return ResourceManager.GetString("IsErrorLimitLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã vượt quá {2} kí tự..
        /// </summary>
        public static string IsErrorLimitLengthMultiple {
            get {
                return ResourceManager.GetString("IsErrorLimitLengthMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép để trống..
        /// </summary>
        public static string IsNotEmpty {
            get {
                return ResourceManager.GetString("IsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string Miss {
            get {
                return ResourceManager.GetString("Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F44336.
        /// </summary>
        public static string MissColor {
            get {
                return ResourceManager.GetString("MissColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép để trống..
        /// </summary>
        public static string NotEmprtyEmail {
            get {
                return ResourceManager.GetString("NotEmprtyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFA07A.
        /// </summary>
        public static string PendingColor {
            get {
                return ResourceManager.GetString("PendingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string SendPending {
            get {
                return ResourceManager.GetString("SendPending", resourceCulture);
            }
        }
    }
}
